In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]

In [3]:
corpus

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?']

In [4]:
vectorizer = CountVectorizer()

In [5]:
X = vectorizer.fit_transform(corpus)

In [6]:
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [7]:
vectorizer.vocabulary_

{'this': 8,
 'is': 3,
 'the': 6,
 'first': 2,
 'document': 1,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}

In [8]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [9]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [10]:
vectorizer.get_stop_words()

In [11]:
vectorizer.inverse_transform(X.toarray())

[array(['document', 'first', 'is', 'the', 'this'], dtype='<U8'),
 array(['document', 'is', 'second', 'the', 'this'], dtype='<U8'),
 array(['and', 'is', 'one', 'the', 'third', 'this'], dtype='<U8'),
 array(['document', 'first', 'is', 'the', 'this'], dtype='<U8')]